import React from "react";

// ─── Styles ──────────────────────────────────────────────────────────────────

export const styles: Record<string, React.CSSProperties | Record<string, unknown>> = {
    // Header
    toolbar: {
        "--background": "var(--color-surface)",
        "--border-color": "var(--color-border)",
        "--padding-start": "0",
        "--padding-end": "0",
    } as React.CSSProperties,
    headerInner: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        padding: "0 var(--space-3)",
        height: "56px",
    },
    menuButton: {
        color: "var(--color-text-secondary)",
        "--color": "var(--color-text-secondary)",
    } as React.CSSProperties,
    sessionName: {
        fontFamily: "var(--font-display)",
        fontSize: "var(--text-heading)",
        fontWeight: 600,
        color: "var(--color-text-primary)",
        letterSpacing: "-0.02em",
        lineHeight: 1.2,
        margin: 0,
        flex: 1,
        textAlign: "center",
        overflow: "hidden",
        textOverflow: "ellipsis",
        whiteSpace: "nowrap",
        minWidth: 0,
    },
    joinCodeButton: {
        background: "none",
        border: "none",
        cursor: "pointer",
        padding: "var(--space-2)",
        minWidth: "44px",
        minHeight: "44px",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
    },
    joinCodeIcon: {
        fontSize: "20px",
        color: "var(--color-text-secondary)",
    },

    // Player switcher (rendered inside IonHeader — never scrolls)
    switcherWrap: {
        backgroundColor: "var(--color-surface)",
        borderBottom: "1.5px solid var(--color-border)",
        boxShadow: "0 2px 8px rgba(0, 0, 0, 0.3)",
    },
    switcherStrip: {
        display: "flex",
        flexDirection: "row",
        overflowX: "auto",
        gap: "var(--space-2)",
        padding: "var(--space-2) var(--space-4)",
        WebkitOverflowScrolling: "touch",
        alignItems: "center",
    },
    // ── Shared pill base ──────────────────────────────────────────────────────
    pillActive: {
        background: "var(--color-accent-primary)",
        clipPath:
            "polygon(4px 0%, calc(100% - 4px) 0%, 100% 4px, 100% calc(100% - 4px), calc(100% - 4px) 100%, 4px 100%, 0% calc(100% - 4px), 0% 4px)",
        boxShadow:
            "inset 0 1.5px 0 0 rgba(240, 237, 228, 0.22), inset 0 0 0 1.5px rgba(212, 168, 71, 0.45)",
        color: "var(--color-bg)",
        fontFamily: "var(--font-ui)",
        fontSize: "var(--text-subheading)",
        fontWeight: 700,
        letterSpacing: "-0.01em",
        padding: "0 var(--space-5)",
        height: "48px",
        whiteSpace: "nowrap",
        cursor: "pointer",
        flexShrink: 0,
        animation:
            "pillActivate 220ms cubic-bezier(0.22, 1, 0.36, 1) both, playerTokenGlow 2.4s ease-in-out infinite 220ms",
        transition:
            "color 200ms cubic-bezier(0.22, 1, 0.36, 1), background 200ms cubic-bezier(0.22, 1, 0.36, 1), box-shadow 200ms cubic-bezier(0.22, 1, 0.36, 1)",
        minWidth: "72px",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        userSelect: "none",
        WebkitUserSelect: "none",
        WebkitTouchCallout: "none",
        touchAction: "manipulation",
    },
    pillInactive: {
        background: "var(--color-surface-elevated)",
        clipPath:
            "polygon(3px 0%, calc(100% - 3px) 0%, 100% 3px, 100% calc(100% - 3px), calc(100% - 3px) 100%, 3px 100%, 0% calc(100% - 3px), 0% 3px)",
        boxShadow:
            "inset 0 0 0 1px color-mix(in srgb, var(--color-accent-primary) 45%, transparent)",
        color: "var(--color-text-secondary)",
        fontFamily: "var(--font-ui)",
        fontSize: "var(--text-caption)",
        fontWeight: 400,
        padding: "0 var(--space-3)",
        height: "38px",
        whiteSpace: "nowrap",
        cursor: "pointer",
        flexShrink: 0,
        transition:
            "color 200ms var(--ease), background 200ms var(--ease), box-shadow 200ms var(--ease), opacity 200ms var(--ease)",
        minWidth: "52px",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        userSelect: "none",
        WebkitUserSelect: "none",
        WebkitTouchCallout: "none",
        touchAction: "manipulation",
    },
    pillNonDevice: {
        background:
            "color-mix(in srgb, var(--color-accent-amber) 7%, var(--color-surface-elevated))",
        clipPath:
            "polygon(3px 0%, calc(100% - 3px) 0%, 100% 3px, 100% calc(100% - 3px), calc(100% - 3px) 100%, 3px 100%, 0% calc(100% - 3px), 0% 3px)",
        boxShadow: "inset 0 0 0 1px color-mix(in srgb, var(--color-accent-amber) 35%, transparent)",
        color: "var(--color-accent-amber)",
        fontFamily: "var(--font-ui)",
        fontSize: "var(--text-caption)",
        fontWeight: 400,
        padding: "0 var(--space-3)",
        height: "40px",
        whiteSpace: "nowrap",
        cursor: "pointer",
        flexShrink: 0,
        opacity: 0.65,
        transition:
            "color 200ms var(--ease), background 200ms var(--ease), box-shadow 200ms var(--ease), opacity 200ms var(--ease)",
        minWidth: "52px",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        userSelect: "none",
        WebkitUserSelect: "none",
        WebkitTouchCallout: "none",
        touchAction: "manipulation",
    },
    pillNonDeviceActive: {
        background: "var(--color-accent-amber)",
        clipPath:
            "polygon(4px 0%, calc(100% - 4px) 0%, 100% 4px, 100% calc(100% - 4px), calc(100% - 4px) 100%, 4px 100%, 0% calc(100% - 4px), 0% 4px)",
        boxShadow:
            "inset 0 1.5px 0 0 rgba(240, 237, 228, 0.18), inset 0 0 0 1.5px rgba(240, 237, 228, 0.12)",
        filter: "drop-shadow(0 0 16px rgba(212, 168, 71, 0.55))",
        animation: "pillActivate 220ms cubic-bezier(0.22, 1, 0.36, 1) both",
        color: "var(--color-bg)",
        fontFamily: "var(--font-ui)",
        fontSize: "var(--text-subheading)",
        fontWeight: 700,
        letterSpacing: "-0.01em",
        padding: "0 var(--space-5)",
        height: "48px",
        whiteSpace: "nowrap",
        cursor: "pointer",
        flexShrink: 0,
        opacity: 1,
        transition:
            "color 200ms cubic-bezier(0.22, 1, 0.36, 1), background 200ms cubic-bezier(0.22, 1, 0.36, 1), box-shadow 200ms cubic-bezier(0.22, 1, 0.36, 1)",
        minWidth: "72px",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        userSelect: "none",
        WebkitUserSelect: "none",
        WebkitTouchCallout: "none",
        touchAction: "manipulation",
    },
    pillName: {
        fontFamily: "var(--font-display)",
        fontSize: "inherit",
        letterSpacing: "-0.02em",
        fontStyle: "italic",
        userSelect: "none",
        WebkitUserSelect: "none",
        WebkitTouchCallout: "none",
        overflow: "hidden",
        textOverflow: "ellipsis",
        maxWidth: "120px",
    },
    avatarActive: {},
    avatarInactive: {},
    avatarNonDevice: {},
    avatarNonDeviceActive: {},
    // Left (inactive) device player pills
    pillLeft: {
        background: "var(--color-surface)",
        clipPath:
            "polygon(3px 0%, calc(100% - 3px) 0%, 100% 3px, 100% calc(100% - 3px), calc(100% - 3px) 100%, 3px 100%, 0% calc(100% - 3px), 0% 3px)",
        boxShadow: "inset 0 0 0 1px color-mix(in srgb, var(--color-border) 40%, transparent)",
        color: "var(--color-text-secondary)",
        fontFamily: "var(--font-ui)",
        fontSize: "var(--text-caption)",
        fontWeight: 400,
        padding: "0 var(--space-3)",
        height: "36px",
        whiteSpace: "nowrap",
        cursor: "pointer",
        flexShrink: 0,
        opacity: 0.45,
        transition:
            "color 200ms var(--ease), background 200ms var(--ease), opacity 200ms var(--ease)",
        minWidth: "52px",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        userSelect: "none",
        WebkitUserSelect: "none",
        WebkitTouchCallout: "none",
        touchAction: "manipulation",
    },
    pillLeftActive: {
        background: "color-mix(in srgb, var(--color-text-secondary) 8%, var(--color-surface))",
        clipPath:
            "polygon(3px 0%, calc(100% - 3px) 0%, 100% 3px, 100% calc(100% - 3px), calc(100% - 3px) 100%, 3px 100%, 0% calc(100% - 3px), 0% 3px)",
        boxShadow: "inset 0 0 0 1px var(--color-border)",
        color: "var(--color-text-secondary)",
        fontFamily: "var(--font-ui)",
        fontSize: "var(--text-caption)",
        fontWeight: 500,
        padding: "0 var(--space-3)",
        height: "40px",
        whiteSpace: "nowrap",
        cursor: "pointer",
        flexShrink: 0,
        opacity: 0.7,
        transition:
            "color 200ms var(--ease), background 200ms var(--ease), opacity 200ms var(--ease)",
        minWidth: "52px",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        userSelect: "none",
        WebkitUserSelect: "none",
        WebkitTouchCallout: "none",
        touchAction: "manipulation",
    },
    avatarLeft: {},
    avatarLeftActive: {},
    viewingBanner: {
        textAlign: "center",
        fontSize: "var(--text-caption)",
        fontFamily: "var(--font-ui)",
        color: "var(--color-accent-amber)",
        letterSpacing: "0.08em",
        textTransform: "uppercase",
        padding: "var(--space-1) var(--space-4)",
        borderBottom: "1px solid color-mix(in srgb, var(--color-accent-amber) 20%, transparent)",
        backgroundColor: "color-mix(in srgb, var(--color-accent-amber) 6%, transparent)",
    },
    pillAdd: {
        background: "transparent",
        clipPath:
            "polygon(3px 0%, calc(100% - 3px) 0%, 100% 3px, 100% calc(100% - 3px), calc(100% - 3px) 100%, 3px 100%, 0% calc(100% - 3px), 0% 3px)",
        boxShadow:
            "inset 0 0 0 1.5px color-mix(in srgb, var(--color-accent-primary) 50%, transparent)",
        color: "color-mix(in srgb, var(--color-accent-primary) 70%, transparent)",
        fontSize: "22px",
        fontWeight: 300,
        lineHeight: 1,
        width: "38px",
        height: "38px",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        cursor: "pointer",
        flexShrink: 0,
        transition:
            "color 200ms var(--ease), background 200ms var(--ease), box-shadow 200ms var(--ease), opacity 200ms var(--ease)",
        userSelect: "none",
        WebkitUserSelect: "none",
        WebkitTouchCallout: "none",
        touchAction: "manipulation",
    },

    // AddPlayerModal
    addPlayerSheet: {
        backgroundColor: "var(--color-surface)",
        clipPath:
            "polygon(10px 0%, calc(100% - 10px) 0%, 100% 10px, 100% calc(100% - 10px), calc(100% - 10px) 100%, 10px 100%, 0% calc(100% - 10px), 0% 10px)",
        boxShadow: "inset 0 0 0 1px var(--color-border)",
        width: "calc(100% - 2 * var(--space-5))",
        maxWidth: "380px",
        padding: "var(--space-6) var(--space-5) var(--space-5)",
        display: "flex",
        flexDirection: "column",
        gap: "var(--space-3)",
    },
    addPlayerTitle: {
        fontFamily: "var(--font-display)",
        fontSize: "var(--text-heading)",
        fontWeight: 600,
        color: "var(--color-text-primary)",
        margin: 0,
        letterSpacing: "-0.02em",
    },
    addPlayerHint: {
        fontFamily: "var(--font-ui)",
        fontSize: "var(--text-body)",
        color: "var(--color-text-secondary)",
        margin: 0,
        lineHeight: 1.4,
    },
    addPlayerForm: {
        display: "flex",
        flexDirection: "column",
        gap: "var(--space-3)",
    },
    addPlayerInput: {
        background: "var(--color-bg)",
        border: "1px solid var(--color-border)",
        color: "var(--color-text-primary)",
        fontFamily: "var(--font-ui)",
        fontSize: "var(--text-body)",
        padding: "var(--space-3) var(--space-4)",
        width: "100%",
        outline: "none",
        boxSizing: "border-box" as const,
    },
    addPlayerError: {
        fontFamily: "var(--font-ui)",
        fontSize: "var(--text-caption)",
        color: "var(--color-danger)",
        margin: 0,
    },
    addPlayerActions: {
        display: "flex",
        flexDirection: "row",
        gap: "var(--space-3)",
        marginTop: "var(--space-1)",
    },
    addPlayerCancel: {
        flex: 1,
        background: "none",
        border: "1px solid var(--color-border)",
        color: "var(--color-text-secondary)",
        fontFamily: "var(--font-ui)",
        fontSize: "var(--text-body)",
        padding: "var(--space-3)",
        cursor: "pointer",
        minHeight: "44px",
    },
    addPlayerJoin: {
        flex: 1,
        background: "var(--color-accent-amber)",
        border: "none",
        color: "var(--color-bg)",
        fontFamily: "var(--font-ui)",
        fontSize: "var(--text-body)",
        fontWeight: 600,
        padding: "var(--space-3)",
        cursor: "pointer",
        minHeight: "44px",
        transition: "opacity 150ms var(--ease)",
    },

    // Card carousel
    contentArea: {
        padding: "var(--space-5)",
        paddingBottom: "var(--space-8)",
        display: "flex",
        flexDirection: "column",
        gap: "var(--space-4)",
    },
    carouselOuter: {
        display: "flex",
        flexDirection: "column",
        gap: "var(--space-3)",
        paddingBottom: "var(--space-6)",
        userSelect: "none",
        WebkitUserSelect: "none",
    },
    resolvedToggle: {
        background: "none",
        border: "none",
        fontFamily: "var(--font-ui)",
        fontSize: "var(--text-caption)",
        color: "var(--color-text-secondary)",
        cursor: "pointer",
        padding: "0 0 var(--space-2) 0",
        textAlign: "center",
        width: "100%",
    },
    cornerDiamond: {
        position: "absolute",
        fontSize: 10,
        color: "var(--color-border)",
        lineHeight: 1,
        pointerEvents: "none",
    },
    resolvedOverlay: {
        position: "absolute",
        inset: 0,
        background: "color-mix(in srgb, var(--color-accent-amber) 20%, transparent)",
        pointerEvents: "none",
        zIndex: 1,
    },
    resolvedBadge: {
        position: "absolute",
        top: "var(--space-3)",
        right: "var(--space-4)",
        fontFamily: "var(--font-ui)",
        fontSize: "var(--text-label)",
        fontWeight: 500,
        color: "var(--color-accent-amber)",
        letterSpacing: "0.15em",
        zIndex: 2,
    },
    // Empty state
    emptyState: {
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        padding: "var(--space-12) var(--space-5)",
        gap: "var(--space-3)",
    },
    emptyLogo: {
        fontFamily: "var(--font-display)",
        fontSize: "64px",
        fontWeight: 700,
        color: "var(--color-border)",
        lineHeight: 1,
        letterSpacing: "-0.02em",
    },
    emptyTitle: {
        fontFamily: "var(--font-ui)",
        fontSize: "var(--text-body)",
        color: "var(--color-text-secondary)",
        margin: 0,
        textAlign: "center",
    },
    emptyHint: {
        fontFamily: "var(--font-ui)",
        fontSize: "var(--text-caption)",
        color: "var(--color-text-secondary)",
        margin: 0,
        textAlign: "center",
        opacity: 0.6,
    },

    // Draw button footer
    footer: {
        backgroundColor: "var(--color-bg)",
        borderTop: "1px solid var(--color-border)",
        padding: "var(--space-4)",
        paddingBottom: "calc(var(--space-4) + env(safe-area-inset-bottom))",
    },
    drawButton: {
        width: "100%",
        height: "56px",
        background: "var(--color-surface)",
        border: "1.5px solid",
        fontFamily: "var(--font-display)",
        fontSize: "var(--text-label)",
        fontWeight: 700,
        letterSpacing: "0.15em",
        transition: "border-color 220ms var(--ease), color 220ms var(--ease)",
    },
    reparationsLink: {
        background: "none",
        border: "none",
        fontFamily: "var(--font-ui)",
        fontSize: "var(--text-caption)",
        color: "var(--color-text-secondary)",
        opacity: 0.6,
        cursor: "pointer",
        padding: "var(--space-2) 0 0",
        textAlign: "center" as const,
        width: "100%",
        letterSpacing: "0.04em",
        transition: "opacity 160ms var(--ease)",
    },

    // Error
    error: {
        fontFamily: "var(--font-ui)",
        fontSize: "var(--text-caption)",
        color: "var(--color-danger)",
        margin: 0,
        textAlign: "center",
    },
    retryLink: {
        background: "none",
        border: "none",
        fontFamily: "var(--font-ui)",
        fontSize: "var(--text-caption)",
        color: "var(--color-accent-primary)",
        cursor: "pointer",
        padding: 0,
        textDecoration: "underline",
    },
    endedBanner: {
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        gap: "var(--space-2)",
        padding: "var(--space-4) var(--space-5)",
        margin: "var(--space-4) 0",
        border: "1px solid var(--color-border)",
        borderRadius: "4px",
        backgroundColor: "var(--color-surface)",
    },
    endedTitle: {
        fontFamily: "var(--font-ui)",
        fontSize: "var(--text-body)",
        color: "var(--color-text-secondary)",
        margin: 0,
        letterSpacing: "0.04em",
    },
    recapLink: {
        background: "none",
        border: "none",
        fontFamily: "var(--font-ui)",
        fontSize: "var(--text-body)",
        color: "var(--color-accent-amber)",
        cursor: "pointer",
        padding: 0,
        letterSpacing: "0.04em",
    },

    // Overlays — shared
    overlayBackdrop: {
        position: "fixed",
        inset: 0,
        zIndex: 100,
        backgroundColor: "color-mix(in srgb, var(--color-bg) 97%, transparent)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        padding: "var(--space-5)",
    },

    // CardRevealOverlay
    gcLogoWrap: {
        position: "absolute",
        top: "50%",
        left: "50%",
        transform: "translate(-50%, -50%)",
        width: "90%",
        zIndex: 10,
        pointerEvents: "none",
    },
    gcLogoImgEnter: {
        width: "100%",
        height: "auto",
        display: "block",
        animation: "gcLogoEnter 500ms cubic-bezier(0.25, 0, 0.1, 1) forwards, gcLogoFloat 2.2s ease-in-out 500ms infinite",
    },
    gcLogoImgExit: {
        width: "100%",
        height: "auto",
        display: "block",
        animation: "gcLogoExit 220ms cubic-bezier(0.55, 0, 1, 0.45) forwards",
    },
    revealCardWrap: {
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        gap: "var(--space-4)",
        width: "100%",
        maxWidth: "430px",
        animation: "cardDeal 380ms var(--ease) forwards",
    },
    revealTitle: {
        fontFamily: "var(--font-display)",
        fontSize: "28px",
        fontWeight: 700,
        color: "var(--color-text-primary)",
        letterSpacing: "-0.02em",
        lineHeight: 1.2,
        margin: 0,
        display: "-webkit-box",
        WebkitBoxOrient: "vertical" as const,
        WebkitLineClamp: 2,
        overflow: "hidden",
        textOverflow: "ellipsis",
    } as React.CSSProperties,
    revealPlayerChip: {
        fontFamily: "var(--font-ui)",
        fontSize: "var(--text-caption)",
        color: "var(--color-text-secondary)",
        margin: 0,
    },
    revealDescription: {
        fontFamily: "var(--font-ui)",
        fontSize: "var(--text-body)",
        color: "var(--color-text-primary)",
        lineHeight: 1.5,
        margin: 0,
        flex: 1,
        minHeight: 0,
        overflow: "auto",
        paddingRight: "8px",
        scrollBehavior: "smooth",
        WebkitOverflowScrolling: "touch",
        display: "block",
    } as React.CSSProperties & {
        scrollbarWidth?: string;
        scrollbarColor?: string;
    },
    hiddenDescArea: {
        background:
            "repeating-linear-gradient(45deg, color-mix(in srgb, var(--color-border) 30%, transparent) 0px, color-mix(in srgb, var(--color-border) 30%, transparent) 1px, transparent 1px, transparent 8px)",
        border: "1px solid var(--color-border)",
        padding: "var(--space-5)",
        cursor: "pointer",
        width: "100%",
        boxSizing: "border-box",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
    },
    hiddenDescLabel: {
        fontFamily: "var(--font-ui)",
        fontSize: "var(--text-caption)",
        color: "var(--color-text-secondary)",
        letterSpacing: "0.05em",
    },
    shareDescBtn: {
        background: "none",
        border: "1px solid var(--color-accent-primary)",
        color: "var(--color-accent-primary)",
        fontFamily: "var(--font-ui)",
        fontSize: "var(--text-label)",
        fontWeight: 500,
        letterSpacing: "0.1em",
        padding: "var(--space-2) var(--space-4)",
        cursor: "pointer",
        alignSelf: "flex-start",
        minHeight: "44px",
    },
    revealDismissHint: {
        fontFamily: "var(--font-ui)",
        fontSize: "var(--text-caption)",
        color: "var(--color-text-secondary)",
        margin: 0,
        textAlign: "center",
    },

    // CardDetailOverlay
    detailWrap: {
        position: "fixed",
        inset: 0,
        zIndex: 100,
        backgroundColor: "var(--color-bg)",
        display: "flex",
        flexDirection: "column",
        paddingTop: "env(safe-area-inset-top)",
        paddingBottom: "env(safe-area-inset-bottom)",
        cursor: "pointer",
    },
    detailCardArea: {
        flex: 1,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        padding: "var(--space-3) var(--space-5)",
        minHeight: 0,
    },

    // Transfer picker
    transferPicker: {
        background: "var(--color-surface-elevated)",
        border: "1px solid var(--color-border)",
        padding: "var(--space-4)",
        display: "flex",
        flexDirection: "column",
        gap: "var(--space-2)",
    },
    transferPickerLabel: {
        fontFamily: "var(--font-ui)",
        fontSize: "var(--text-label)",
        fontWeight: 500,
        color: "var(--color-text-secondary)",
        letterSpacing: "0.15em",
        margin: 0,
    },
    transferPlayerBtn: {
        background: "var(--color-surface)",
        border: "1px solid var(--color-border)",
        color: "var(--color-text-primary)",
        fontFamily: "var(--font-ui)",
        fontSize: "var(--text-body)",
        padding: "var(--space-3) var(--space-4)",
        cursor: "pointer",
        textAlign: "left",
        minHeight: "44px",
        overflow: "hidden",
        textOverflow: "ellipsis",
        whiteSpace: "nowrap",
        width: "100%",
        boxSizing: "border-box" as const,
    },
    transferCancelBtn: {
        background: "none",
        border: "none",
        fontFamily: "var(--font-ui)",
        fontSize: "var(--text-caption)",
        color: "var(--color-text-secondary)",
        cursor: "pointer",
        padding: "var(--space-2) 0",
        textAlign: "left",
        minHeight: "44px",
    },

    // Action bar
    actionBar: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "space-around",
        borderTop: "1px solid var(--color-border)",
        backgroundColor: "var(--color-surface)",
        padding: "var(--space-3) var(--space-2)",
        paddingBottom: "calc(var(--space-3) + env(safe-area-inset-bottom))",
    },
    actionBtn: {
        background: "none",
        border: "none",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        gap: "var(--space-1)",
        cursor: "pointer",
        minWidth: "44px",
        minHeight: "44px",
        justifyContent: "center",
        padding: "0 var(--space-2)",
    },
    actionIcon: {
        fontSize: "20px",
        lineHeight: 1,
    },
    actionLabel: {
        fontFamily: "var(--font-ui)",
        fontSize: "var(--text-label)",
        fontWeight: 500,
        color: "var(--color-text-secondary)",
        letterSpacing: "0.05em",
    },

    // JoinCodeModal
    joinCodeModal: {
        background: "var(--color-surface-elevated)",
        border: "1px solid var(--color-accent-amber)",
        padding: "var(--space-8) var(--space-6)",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        gap: "var(--space-4)",
        position: "relative",
        maxWidth: "320px",
        width: "100%",
        clipPath:
            "polygon(8px 0%, calc(100% - 8px) 0%, 100% 8px, 100% calc(100% - 8px), calc(100% - 8px) 100%, 8px 100%, 0% calc(100% - 8px), 0% 8px)",
    },
    joinCodeClose: {
        position: "absolute",
        top: "var(--space-3)",
        right: "var(--space-3)",
        background: "none",
        border: "none",
        fontFamily: "var(--font-ui)",
        fontSize: "20px",
        color: "var(--color-text-secondary)",
        cursor: "pointer",
        minWidth: "44px",
        minHeight: "44px",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
    },
    joinCodeLabel: {
        fontFamily: "var(--font-ui)",
        fontSize: "var(--text-label)",
        fontWeight: 500,
        color: "var(--color-text-secondary)",
        letterSpacing: "0.15em",
        margin: 0,
    },
    joinCodeDisplay: {
        fontFamily: "var(--font-display)",
        fontSize: "var(--text-display)",
        fontWeight: 700,
        color: "var(--color-accent-amber)",
        letterSpacing: "0.08em",
        margin: 0,
    },
    joinCodeSub: {
        fontFamily: "var(--font-ui)",
        fontSize: "var(--text-caption)",
        color: "var(--color-text-secondary)",
        margin: 0,
        textAlign: "center",
    },
};
